#1. What is K-Nearest Neighbors (KNN) and how does it work in both classification and regression problems?

K-Nearest Neighbors (KNN) is a simple, non-parametric, instance-based (lazy) learning algorithm.
It doesn’t learn a model during training—instead, it stores the data and makes predictions only when a new data point arrives.

Step-by-step: How KNN works:-
1. Choose K:

K = number of neighbors to consider

Small K → sensitive to noise

Large K → smoother but may underfit

2. Choose a distance metric:

Common ones:

Euclidean distance (most common)

d(x,y)=∑(xi​−yi​)2
​

3. Find K nearest neighbors:

Compute distances → sort → select closest K points

KNN for Classification:-

Prediction rule:

Use majority voting among the K neighbors.

KNN for Regression:-

Prediction rule:

Take the average of the target values of K neighbors.



#2. What is the Curse of Dimensionality and how does it affect KNN performance?

In machine learning, the Curse of Dimensionality refers to various phenomena that arise when analyzing and organizing data in high-dimensional spaces (often hundreds or thousands of dimensions) that do not occur in low-dimensional settings like 2D or 3D.

How It Affects K-Nearest Neighbors (KNN):-

KNN is particularly vulnerable because it is a distance-based algorithm. It relies on the assumption that "near" points are similar. Here is how the curse degrades its performance:

1. Distance Concentration:-

In high dimensions, the difference between the distance to the nearest neighbor and the distance to the farthest neighbor becomes negligible.

The Result: Every point becomes almost equidistant from every other point. If all neighbors are "equally far away," the concept of a "nearest" neighbor becomes meaningless.

2. Data Sparsity:-

To maintain the same level of "density" in your data as you add dimensions, the number of data points needed grows exponentially.Example: If you need 10 points to cover a 1D line, you’d need $10^2 = 100$ points for a 2D square, and $10^{10}$ points for a 10-dimensional hypercube.

3. Computational Overload:-

KNN is "lazy," meaning it does most of its work during inference (testing).

The Result: Calculating distances (like Euclidean distance) across 1,000 dimensions for every single query is computationally expensive and significantly slows down the model.

#3. What is Principal Component Analysis (PCA)? How is it different from feature selection?

What is Principal Component Analysis (PCA):-

PCA is an unsupervised dimensionality reduction technique that transforms the original features into a new set of orthogonal (uncorrelated) features called principal components.

These components:

Are linear combinations of original features

Are ordered by maximum variance explained

Capture most information using fewer dimensions

How PCA works (step-by-step):-

1️. Standardize the data
(critical because PCA is variance-based)

2️. Compute covariance matrix

3️. Find eigenvectors & eigenvalues

Eigenvectors → directions (principal components)

Eigenvalues → importance (variance explained)

4️. Sort components by variance

5️. Project data onto top K components

Key properties of PCA:-

Unsupervised

Linear transformation

Components are uncorrelated

Loses some interpretability

Sensitive to scaling

| Aspect                    | PCA                        | Feature Selection     |
| ------------------------- | -------------------------- | --------------------- |
| Approach                  | Feature **transformation** | Feature **selection** |
| Output features           | New (PC1, PC2, …)          | Original features     |
| Supervision               | Unsupervised               | Can be supervised     |
| Interpretability          | Low                        | High                  |
| Handles multicollinearity | Yes                        | Partially             |
| Data leakage risk         | Higher (if misused)        | Lower                 |
| Model dependence          | Model-agnostic             | Sometimes model-based |




#4. What are eigenvalues and eigenvectors in PCA, and why are they important?

What are eigenvectors and eigenvalues in PCA?

In PCA, we start with the covariance matrix of the data.

Eigenvectors:-

Eigenvectors define the directions (axes) along which the data varies

Each eigenvector = a principal component

They show where the data is stretched.

Eigenvalues:-

Eigenvalues measure how much variance exists along each eigenvector

Larger eigenvalue = more information captured

They tell how important each principal component is.

Role in PCA (step-by-step):-

1️. Compute covariance matrix

2️. Compute eigenvectors & eigenvalues

3️. Sort eigenvalues in descending order

4️. Select top K eigenvectors

5️. Project data onto them.

Why are they important in PCA?:-

1️. Identify principal components

Eigenvectors = principal axes

PCA would not know which direction to project data without them.

2️. Decide how many components to keep

Eigenvalues tell variance explained

Explained Variance Ratio=∑λλi​​

3️. Dimensionality reduction

Drop eigenvectors with small eigenvalues

These directions add noise, not information

4️. Remove multicollinearity

Eigenvectors are orthogonal (uncorrelated)

Makes distance-based and linear models stable

#5.  How do KNN and PCA complement each other when applied in a single pipeline?

How PCA helps KNN:-

1️. Reduces dimensionality

PCA keeps only the most informative components

Removes low-variance (mostly noise) directions.

2️. Removes multicollinearity

PCA produces orthogonal (uncorrelated) components

Prevents correlated features from dominating distance.

3️. Improves KNN accuracy

Less noise → better neighbor selection

Smoother decision boundaries.

4️. Makes KNN faster

Distance computation:

O(n×d)

5️. Helps visualization & intuition

PCA → 2D/3D projection

KNN decision boundaries become interpretable.

| Aspect           | KNN Alone | PCA + KNN |
| ---------------- | --------- | --------- |
| Dimensionality   | High      | Reduced   |
| Distance quality | Poor      | Improved  |
| Speed            | Slow      | Faster    |
| Accuracy         | Lower     | Higher    |



In [1]:
#6. Train a KNN Classifier on the Wine dataset with and without feature scaling.
#   Compare model accuracy in both cases.
#   (Include your Python code and output in the code box below.)

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# Load dataset
X, y = load_wine(return_X_y=True)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

# ------------------
# KNN without scaling
# ------------------
knn_no_scaling = KNeighborsClassifier(n_neighbors=5)
knn_no_scaling.fit(X_train, y_train)
y_pred_no_scaling = knn_no_scaling.predict(X_test)
acc_no_scaling = accuracy_score(y_test, y_pred_no_scaling)

# ------------------
# KNN with scaling
# ------------------
pipeline_scaling = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=5))
])

pipeline_scaling.fit(X_train, y_train)
y_pred_scaling = pipeline_scaling.predict(X_test)
acc_scaling = accuracy_score(y_test, y_pred_scaling)

acc_no_scaling, acc_scaling


(0.7777777777777778, 0.9333333333333333)

In [2]:
#7. Train a PCA model on the Wine dataset and print the explained variance
#   ratio of each principal component.
#   (Include your Python code and output in the code box below.)

from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Load dataset
X, y = load_wine(return_X_y=True)

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply PCA (keep all components)
pca = PCA()
X_pca = pca.fit_transform(X_scaled)

# Explained variance ratio
explained_variance = pca.explained_variance_ratio_

explained_variance


array([0.36198848, 0.1920749 , 0.11123631, 0.0706903 , 0.06563294,
       0.04935823, 0.04238679, 0.02680749, 0.02222153, 0.01930019,
       0.01736836, 0.01298233, 0.00795215])

In [3]:
#8. Train a KNN Classifier on the PCA-transformed dataset (retain top 2 components).
#   Compare the accuracy with the original dataset.
#   (Include your Python code and output in the code box below.)

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# Load dataset
X, y = load_wine(return_X_y=True)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

# -------------------------------
# KNN on original (scaled) dataset
# -------------------------------
pipeline_original = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=5))
])

pipeline_original.fit(X_train, y_train)
y_pred_original = pipeline_original.predict(X_test)
acc_original = accuracy_score(y_test, y_pred_original)

# -------------------------------
# KNN on PCA-transformed dataset
# (retain top 2 components)
# -------------------------------
pipeline_pca = Pipeline([
    ("scaler", StandardScaler()),
    ("pca", PCA(n_components=2)),
    ("knn", KNeighborsClassifier(n_neighbors=5))
])

pipeline_pca.fit(X_train, y_train)
y_pred_pca = pipeline_pca.predict(X_test)
acc_pca = accuracy_score(y_test, y_pred_pca)

acc_original, acc_pca


(0.9333333333333333, 0.9333333333333333)

In [4]:
#9. Train a KNN Classifier with different distance metrics (euclidean, manhattan)
#   on the scaled Wine dataset and compare the results.
#   (Include your Python code and output in the code box below.)

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

# 1. Load the Wine dataset
wine = load_wine()
X, y = wine.data, wine.target

# 2. Split into training and testing sets (80/20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Scale the data (Crucial for distance-based models!)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. Define and train KNN with Euclidean Distance
knn_euclidean = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn_euclidean.fit(X_train_scaled, y_train)
y_pred_euc = knn_euclidean.predict(X_test_scaled)

# 5. Define and train KNN with Manhattan Distance
knn_manhattan = KNeighborsClassifier(n_neighbors=5, metric='manhattan')
knn_manhattan.fit(X_train_scaled, y_train)
y_pred_man = knn_manhattan.predict(X_test_scaled)

# 6. Compare Results
print(f"Euclidean Accuracy: {accuracy_score(y_test, y_pred_euc):.4f}")
print(f"Manhattan Accuracy: {accuracy_score(y_test, y_pred_man):.4f}")

print("\n--- Manhattan Detailed Report ---")
print(classification_report(y_test, y_pred_man))

Euclidean Accuracy: 0.9444
Manhattan Accuracy: 0.9444

--- Manhattan Detailed Report ---
              precision    recall  f1-score   support

           0       0.93      1.00      0.97        14
           1       1.00      0.86      0.92        14
           2       0.89      1.00      0.94         8

    accuracy                           0.94        36
   macro avg       0.94      0.95      0.94        36
weighted avg       0.95      0.94      0.94        36



In [5]:
#10. You are working with a high-dimensional gene expression dataset to
#   classify patients with different types of cancer.
#   Due to the large number of features and a small number of samples, traditional models overfit.
#   Explain how you would:
#   ● Use PCA to reduce dimensionality
#   ● Use KNN for classification post-dimensionality reduction
#   ● Evaluate the model
#   ● Justify this pipeline to your stakeholders as a robust solution for real-world biomedical data

# PCA Dimensionality Reduction:-
# PCA transforms the original features into uncorrelated principal components ordered by explained variance.
# For gene expression data (e.g., thousands of genes), it collapses dimensions while retaining key biological signals.

import numpy as np
from sklearn.decomposition import PCA
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler

# Simulate high-dimensional gene expression data: 100 samples, 5000 genes, 3 cancer types
X, y = make_classification(n_samples=100, n_features=5000, n_informative=50, n_redundant=100,
                          n_clusters_per_class=1, n_classes=3, random_state=42)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(random_state=42)
X_pca = pca.fit_transform(X_scaled)

print("Original shape:", X.shape)
print("PCA-transformed shape:", X_pca.shape)
print("Explained variance ratio (first 10 components):", pca.explained_variance_ratio_[:10])


# Selecting Components:-
# Retain components explaining 95% cumulative variance to balance information retention and dimensionality reduction.
# This data-driven threshold avoids arbitrary cutoffs.

cumulative_variance = np.cumsum(pca.explained_variance_ratio_)
n_components_95 = np.argmax(cumulative_variance >= 0.95) + 1
print(f"Components for 95% variance: {n_components_95}")
print(f"Cumulative variance at {n_components_95} components: {cumulative_variance[n_components_95-1]:.3f}")


# KNN Classification:-
# Apply K-Nearest Neighbors on reduced PCA features. Use cross-validation to tune K, preventing overfitting on limited samples.

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.pipeline import Pipeline

# Pipeline: Scale -> PCA (95% variance) -> KNN
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95, random_state=42)),
    ('knn', KNeighborsClassifier())
])

# Cross-validate with stratified k-fold (critical for imbalanced biomedical data)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
k_values = range(1, 21)
cv_scores = []

for k in k_values:
    pipeline.named_steps['knn'].n_neighbors = k
    scores = cross_val_score(pipeline, X, y, cv=cv, scoring='accuracy')
    cv_scores.append(scores.mean())

best_k = k_values[np.argmax(cv_scores)]
print(f"Best K: {best_k}, CV Accuracy: {max(cv_scores):.3f}")


# Model Evaluation:-
# Use stratified cross-validation with accuracy, precision, recall, and F1-score.
# For cancer classification, prioritize balanced metrics over raw accuracy due to class imbalance.

from sklearn.metrics import classification_report, confusion_matrix

# Final model with best K
pipeline.named_steps['knn'].n_neighbors = best_k
pipeline.fit(X, y)

# Test on holdout (80/20 split simulation)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))




Original shape: (100, 5000)
PCA-transformed shape: (100, 100)
Explained variance ratio (first 10 components): [0.01324716 0.01295231 0.01291452 0.01281986 0.01270359 0.01260164
 0.01256437 0.01254242 0.01238674 0.012337  ]
Components for 95% variance: 93
Cumulative variance at 93 components: 0.954
Best K: 20, CV Accuracy: 0.420
Classification Report:
               precision    recall  f1-score   support

           0       0.43      0.43      0.43         7
           1       0.38      0.71      0.50         7
           2       0.00      0.00      0.00         6

    accuracy                           0.40        20
   macro avg       0.27      0.38      0.31        20
weighted avg       0.28      0.40      0.33        20

Confusion Matrix:
 [[3 4 0]
 [2 5 0]
 [2 4 0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
